version: 2.1
orbs:
  node: circleci/node@5

jobs:
  build-and-deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install

      - run:
          name: Install Hexo CLI
          command: sudo npm install -g hexo-cli
          
      - run:
          name: Generate Hexo Site
          command: hexo generate
          
      - run:
          name: Install gh-pages package
          command: npm install gh-pages --save-dev
          
      - run:
          name: Configure Git
          command: |
            git config --global user.email "ci-build@circleci.com"
            git config --global user.name "CircleCI Build"
            
      - run:
          name: Deploy to GitHub Pages
          command: |
            npx gh-pages -d public -b gh-pages -m "Build generated [skip ci]"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: master