version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build-and-deploy:
    executor:
      name: node/default
      tag: '20'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Install Hexo CLI
          command: npm install -g hexo-cli
      - run:
          name: Generate Hexo Site
          command: hexo generate
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "mmmran@163.com"
            git config --global user.name "unclemartian"
            hexo deploy
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy